### ISSUE TITLE
Fehler bei Installation unter 5.3

### ISSUE THREAD

**Issue by rotzek** [tbaddade/redaxo_cheatsheet#1]
Die beiden Ordner /redaxo/cache/addons/cheatsheet/ und /extension_points/ werden beim Setup nicht angelegt, dann erscheint ein Fehler beim Aufruf des Addons. Nach manuellem Anlegen funktioniert es.

Beim Klick auf "Anzeigen" unter "Core" erscheint kein Inhalt...

**Comment by skerbis** [comment]
> InvalidArgumentException
Folder "/var/www/vhosts/rexdemo.tld.de/httpdocs/redaxo/cache/addons/cheatsheet/extension_points//" not found!

**Comment by olien** [comment]
Bestätige den Fehler von Thomas…

**Comment by AWqxKAWERbXo** [comment]
Kann zu? @rotzek

**Comment by rotzek** [comment]
Funktioniert in der aktuellen redaxo-Version, kann zu... Das Issue ist von 2017 !!!!!!!!!!
