### ISSUE TITLE
countable-Notice mit PHP 7.2

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [tbaddade/redaxo_cheatsheet#9]
kwT

**Comment by tbaddade** [comment]
[Kuwait; Kleinwalsertal?](https://abkuerzungen.woxikon.de/abkuerzung/kwt.php) Kannst du es genauer beschreiben bitte?

**Comment by AWqxKAWERbXo** [comment]
In PHP 7.2 hat sich was geändert:


http://php.net/manual/de/migration72.incompatible.php
An E_WARNING will now be emitted when attempting to count() non-countable types (this includes the sizeof() alias function).

Das Cheatsheet einfach unter PHP 7.2 installieren, dann kommt entsprechend eine Warnung im Backend.

**Comment by tbaddade** [comment]
Danke dir … ich schau es mir an

**Comment by madiko** [comment]
Habe heute die PHP-Version hochgesetzt ( 7-72STABLE // 7.2.11 ) und bekomme die Meldung auch:
Warning: count(): Parameter must be an array or an object that implements Countable in redaxo/src/addons/cheatsheet/boot.php on line 49
